name: Python package

on: [push]

jobs:
  buildmain:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Output test
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python3 parse.py
          python3 generated_tests.py > mainoutput.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: main-output
          path: mainoutput.log

  buildbranch:
    needs: buildmain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: main-output
